version: 2.1
jobs:
  build:
    docker:
      - image: circleci/elixir:1.13

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
            mix credo
            mix test
